### ISSUE TITLE
Pacifica Archive Database

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#52]
# Details 
Would like to discuss with Kevin based on new info if there is anything to be salvaged from this database/worth spending any more time on. 

Submitted by: Rochelle
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
Rochelle will ask them to create a login to their application - as if we're new to their staff.  I can change its permissions after it exists in the database, but I'm not optimistic I can/should simply install it using phpMyAdmin (yikes!) because one of the columns in table 'users' is `pass` and that's a hash of their submitted password AND I DON'T KNOW THE SALT USED FOR THE HASH

**Comment by ekemeyer** [comment]
closing for now, can reopen if more requests for data come up

**Comment by foo4thought** [comment]
ooh, this ticket missed a lot of action.  In summary:

1. I used node values from the database to use lynx to scrape their web site's "print" controller for each node
2. a BASH script parsed the downloaded text and reformatted it into tab-delimited text for each
3. others assembled file system metadata from the contributor organization
4. Rebecca reformatted file system metadata into spreadsheet documents
5. I appended (sheet) and integrated (new columns on existing rows) web site descriptive metadata into the spreadsheets
6. I returned spreadsheets to Rebecca, Rochell, Miranda and Raananah for review
7. Finishing work to be done by an intern from UCLA
