### ISSUE TITLE
Metadata missing from NEH DIGITIZED_ITEMS

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/mla-tickets#73]
# Details 
some subsets of worksheet data from GBAV is now missing 

Submitted by: Rebecca Fraimow
CC in communications: peter_higgins@wgbh.org
Priority: High (within the week)
URL: 
Slack message thread:

**Comment by foo4thought** [comment]
1. exported from database to file all NEH values of DIGITIZED_ITEMS::BARCODE_fk
2. extracted from all relevant local XLSX files (my repo) all values of barcode
3. downloaded all XLSX files from Rebecca's collection on Google drive
4. extracted from all relevant local XLSX files (her repo) all values of barcode
5. installed all data into a spreadsheet to identify gaps
6. reported to Rebecca, who worked with GBAV manager to identify things never sent
7. imported data to DIGITIZED_ITEMS to restore connections for barren records of PRODUCTION
8. repaired a single record of PRODUCTION for which database join failed due to trailing white space
9. reported outcomes to Rebecca
